spring:
  application:
    name: agent-ai
  mongodb:
    uri: mongodb://user:agent123@localhost:27017/chat_memory_db?authSource=admin
    database: chat_memory_db

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG

server:
  port: 8080

client:
  url: http://localhost:4200

ollama:
  model: llama3.2
  host: http://localhost:11434
  timeout: 60
  memory:
    maxMessage: 20