spring:
  application:
    name: agent-ai
data:
  mongodb:
    url: mongodb://localhost:27017/chat_memory_db

server:
  port: 8080

client:
  url: http://localhost:4200

ollama:
  model: llama3.2
  host: http://localhost:11434
  timeout: 60
  memory:
    maxMessage: 20